apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-test
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo-test
spec:
  url: https://charts.example.com   # ✅ Correct placement
  interval: 10m0s

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo-test
spec:
  interval: 5m              # ✅ Required!
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>=6.0.0'
  values:
    replicaCount: 1
    ingress:
      enabled: true
      className: "public"
      hosts:
        - host: podinfo.devplay.art
          paths:
            - path: /
              pathType: Prefix
