apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo-test
  url: https://stefanprodan.github.io/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo-test
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>=6.0.0'
  values:
    replicaCount: 2
    ingress:
      enabled: true
      className: "public"
      hosts:
        - host: podinfo.devplay.art
          paths:
            - path: /
              pathType: Prefix

